name: Build & Deploy to DO VPS
on:
  push:
    paths:
      - "src/**"
      - ".github/**"
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [16]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with: 
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3 
        with: 
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: web/pnpm-lock.yaml
          cache: 'pnpm'

      - name: install dependencies and build
        run: |
          cd web
          pnpm install
          pnpm build

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: "web/dist/*"
          target: "/var/www/chat.daolanfler.xyz/html/"
          strip_components: 2
      # - name: Success bark notify
      #   uses: daolanfler/bark-action@v1
      #   with:
      #     host: ${{ secrets.BARK_HOST }}
      #     key: ${{ secrets.BARK_KEY }}
      #     title: 部署成功
      #     url: https://vite.daolanfler.xyz
      #     body: ${{ github.repository }}[${{ github.sha }}]部署成功
      #   if: ${{ success() }}
      # - name: Failed Bark notify
      #   uses: daolanfler/bark-action@v1
      #   with:
      #     host: ${{ secrets.BARK_HOST }}
      #     key: ${{ secrets.BARK_KEY }}
      #     title: 部署失败
      #     url: https://vite.daolanfler.xyz
      #     body: ${{ github.repository }}[${{ github.sha }}]部署失败
      #   if: ${{ failure() }}
